### ISSUE TITLE
frozen record, no controls

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#12] opened 2022-04-25 16:52 UTC
https://list.worldfloraonline.org/rhakhis/ui/#wfo-1200000001

Added what I thought was a species, cut and paste. it had an extra character between the words. Created a subspecies record, I assume because there is no species part the record doesn't know how to react so all fields are unresponsive.

**Comment by rogerhyam** [comment] 2022-04-26 08:06
Fixed double space issue in code.
Having trouble reproducing the locking.

**Comment by AlanElliott82** [comment] 2022-04-26 08:26
Can you see the frozen record though? no controls or ability to type etc.

**Comment by rogerhyam** [comment] 2022-04-27 09:13
I think the frozen record thing may be when you have a stale user object in the session because when you login it wasn't refreshing the page properly. I believe I've fixed this now. Refreshing the page should generally fix it.

There will still be issues with session time out that need fixing I think but we'll get there.

**Comment by rogerhyam** [comment] 2022-05-06 08:22
Not reproducible so closing.

**Closed by rogerhyam** 2022-05-06 08:22 UTC
Labels: priority:1
